---
kind: pipeline
name: build amd64

platform:
  os: linux
  arch: amd64

steps:
- name: version latest
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: johannweging/platformio
    tags: latest
    username:
      from_secret: docker_username

trigger:
  branch:
  - master

...
